#ifndef QTN_PROPERTYWIDGETAPI_H
#define QTN_PROPERTYWIDGETAPI_H

#if defined(QTN_PE_PROPERTYWIDGET_LIBRARY)
#  define QTN_PW_EXPORT Q_DECL_EXPORT
#else
#  define QTN_PW_EXPORT Q_DECL_IMPORT
#endif

#endif // QTN_PROPERTYWIDGETAPI_H
